# Generated by Django 6.0.7 on 2026-07-29 19:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 29, 19, 59, 23, 10781, tzinfo=datetime.timezone.utc), verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='archetype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Архетип'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_club_member',
            field=models.BooleanField(default=False, verbose_name='Участник закрытого клуба'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('past_due', 'Просрочена'), ('canceled', 'Отменена'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, default=2900.0, max_digits=10, verbose_name='Сумма')),
                ('payment_provider', models.CharField(default='YooKassa', max_length=50, verbose_name='Провайдер платежей')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции/подписки')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Начало подписки')),
                ('next_billing_date', models.DateTimeField(verbose_name='Дата следующего списания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
