# Generated by Django 5.2.16 on 2026-07-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_personal_guidance",
            field=models.BooleanField(
                default=False,
                help_text="Ставится вручную после оплаты индивидуальной работы.",
                verbose_name="Личное ведение («Маг»)",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="auto_renew",
            field=models.BooleanField(
                default=True, verbose_name="Продлевать автоматически"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отменена в"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="archetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seeker", "Искатель"),
                    ("creator", "Творец"),
                    ("sage", "Мудрец"),
                    ("ruler", "Правитель"),
                    ("lover", "Любовник"),
                    ("hero", "Герой"),
                ],
                max_length=20,
                null=True,
                verbose_name="Архетип",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
    ]
