# Generated by Django 5.2.16 on 2026-07-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Екатерина Вершанская",
                        max_length=120,
                        verbose_name="Имя на сайте",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="Психолог, работаю с архетипами",
                        max_length=160,
                        verbose_name="Кто вы",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Понять, кто вы, и перестать жить чужую жизнь",
                        help_text="Слова в *звёздочках* будут выделены курсивом и цветом.",
                        max_length=200,
                        verbose_name="Заголовок первого экрана",
                    ),
                ),
                (
                    "lead",
                    models.TextField(
                        default="Начнём не с советов, а с вопроса о вас. Семь вопросов — и станет видно, какой архетип ведёт вас сейчас, где вы теряете силы и с чего начинать.",
                        verbose_name="Текст под заголовком",
                    ),
                ),
                (
                    "portrait",
                    models.ImageField(
                        blank=True,
                        help_text="Вертикальное фото. Лучше всего 4:5, лицо ближе к верху.",
                        null=True,
                        upload_to="profile/",
                        verbose_name="Портрет",
                    ),
                ),
                (
                    "portrait_note",
                    models.CharField(
                        blank=True,
                        default="Веду разборы с 2019 года",
                        help_text="Маленькая карточка поверх фотографии. Оставьте пустой, чтобы убрать.",
                        max_length=120,
                        verbose_name="Подпись у портрета",
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        blank=True,
                        default="Коротко о себе",
                        max_length=200,
                        verbose_name="Заголовок блока «о себе»",
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True,
                        default="Я не даю универсальных советов и не обещаю, что всё наладится за неделю. Моя работа — помочь увидеть, по какому сценарию вы живёте сейчас и какой шаг в нём действительно ваш.",
                        verbose_name="Текст блока «о себе»",
                    ),
                ),
                (
                    "about_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Необязательно. Показывается в блоке «о себе».",
                        null=True,
                        upload_to="profile/",
                        verbose_name="Второе фото",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Профиль сайта",
                "verbose_name_plural": "Профиль сайта",
            },
        ),
    ]
