# Generated by Django 5.2.16 on 2026-07-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_siteprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("self_employed", "Самозанятый (НПД)"),
                            ("ip", "Индивидуальный предприниматель"),
                            ("ooo", "ООО"),
                        ],
                        default="self_employed",
                        max_length=20,
                        verbose_name="Форма",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        help_text="Например: ИП Вершанская Екатерина Сергеевна",
                        max_length=255,
                        verbose_name="Полное наименование",
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=12, verbose_name="ИНН"),
                ),
                (
                    "ogrn",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="ОГРН / ОГРНИП"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email для обращений"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "site_url",
                    models.URLField(
                        blank=True,
                        help_text="Подставляется в тексты документов.",
                        verbose_name="Адрес сайта",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Реквизиты",
                "verbose_name_plural": "Реквизиты",
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Например: oferta — страница будет /dokumenty/oferta/",
                        unique=True,
                        verbose_name="Адрес",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Одна строка под заголовком, человеческим языком.",
                        max_length=300,
                        verbose_name="Короткое пояснение",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Можно использовать подстановки: {НАИМЕНОВАНИЕ}, {ИНН}, {ОГРН}, {АДРЕС}, {EMAIL}, {ТЕЛЕФОН}, {САЙТ} — они заменятся на реквизиты.",
                        verbose_name="Текст документа",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Черновик виден только сотрудникам.",
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=True, verbose_name="Ссылка в подвале"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Порядок"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Правовой документ",
                "verbose_name_plural": "Правовые документы",
                "ordering": ["order", "id"],
            },
        ),
    ]
