# Generated by Django 5.2.16 on 2026-08-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_legalinfo_legalpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalinfo",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Расчётный счёт"
            ),
        ),
        migrations.AddField(
            model_name="legalinfo",
            name="bank_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Адрес банка"
            ),
        ),
        migrations.AddField(
            model_name="legalinfo",
            name="bank_bik",
            field=models.CharField(blank=True, max_length=9, verbose_name="БИК банка"),
        ),
        migrations.AddField(
            model_name="legalinfo",
            name="bank_corr_account",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Корреспондентский счёт"
            ),
        ),
        migrations.AddField(
            model_name="legalinfo",
            name="bank_inn",
            field=models.CharField(blank=True, max_length=12, verbose_name="ИНН банка"),
        ),
        migrations.AddField(
            model_name="legalinfo",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Банк"),
        ),
    ]
