# Generated by Django 5.2.16 on 2026-07-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Вопрос")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Подсказка под вопросом",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL-слаг")),
                (
                    "intro",
                    models.TextField(blank=True, verbose_name="Текст перед началом"),
                ),
                (
                    "outro",
                    models.TextField(
                        blank=True,
                        help_text="Показывается под результатом, перед призывом к действию.",
                        verbose_name="Текст после результата",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликован"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Квиз",
                "verbose_name_plural": "Квизы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Вариант ответа"),
                ),
                (
                    "archetype",
                    models.CharField(
                        choices=[
                            ("seeker", "Искатель"),
                            ("creator", "Творец"),
                            ("sage", "Мудрец"),
                            ("ruler", "Правитель"),
                            ("lover", "Любовник"),
                            ("hero", "Герой"),
                        ],
                        max_length=20,
                        verbose_name="За какой архетип голосует",
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Вес голоса"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="quiz.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
                verbose_name="Квиз",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        verbose_name="Ключ сессии",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Имя"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "contact_telegram",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram"
                    ),
                ),
                (
                    "result_archetype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("seeker", "Искатель"),
                            ("creator", "Творец"),
                            ("sage", "Мудрец"),
                            ("ruler", "Правитель"),
                            ("lover", "Любовник"),
                            ("hero", "Герой"),
                        ],
                        max_length=20,
                        verbose_name="Определённый архетип",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершён"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Источник трафика"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начат"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершён в"
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.quiz",
                        verbose_name="Квиз",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождение квиза",
                "verbose_name_plural": "Прохождения квиза",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.option",
                        verbose_name="Ответ",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizattempt",
                        verbose_name="Прохождение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ",
                "verbose_name_plural": "Ответы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("attempt", "question"),
                        name="quiz_unique_answer_per_question",
                    )
                ],
            },
        ),
    ]
