# Generated by Django 6.0.7 on 2026-07-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Забронирован')),
            ],
            options={
                'verbose_name': 'Слот для записи',
                'verbose_name_plural': 'Слоты для записи',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на Zoom / Google Meet')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки к встрече / Запрос клиента')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Разбор проведен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Запись на разбор',
                'verbose_name_plural': 'Записи на разборы',
            },
        ),
    ]
