# Generated by Django 5.2.16 on 2026-07-30 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запись на разбор",
                "verbose_name_plural": "Записи на разборы",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="is_canceled",
            field=models.BooleanField(default=False, verbose_name="Отменена"),
        ),
        migrations.AddField(
            model_name="bookingslot",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Снимите галочку, чтобы временно убрать окно.",
                verbose_name="Показывать на сайте",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.bookingslot",
                verbose_name="Слот",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_canceled", False)),
                fields=("slot",),
                name="booking_unique_active_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookingslot",
            constraint=models.UniqueConstraint(
                fields=("start_time",), name="booking_unique_slot_start"
            ),
        ),
    ]
