# Generated by Django 6.0.7 on 2026-07-29 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Обложка')),
                ('access_level', models.CharField(choices=[('free', 'Бесплатный'), ('paid', 'Платный курс'), ('club', 'Только для членов клуба')], default='free', max_length=10, verbose_name='Уровень доступа')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена (если платный)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('video_file', models.FileField(blank=True, help_text='Загрузите видеофайл в формате MP4, MOV, AVI, MKV или WEBM', null=True, upload_to='lessons/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])], verbose_name='Видеофайл (загрузка на сайт)')),
                ('video_url', models.URLField(blank=True, help_text='Используйте, если видео загружено на внешнюю платформу', null=True, verbose_name='Ссылка на видео (альтернатива)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текстовые материалы / Описание')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Доступен для предпросмотра')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
    ]
