# Generated by Django 5.2.16 on 2026-07-30 02:14

import django.core.validators
import django.db.models.deletion
import lms.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["order", "-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="for_archetype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seeker", "Искатель"),
                    ("creator", "Творец"),
                    ("sage", "Мудрец"),
                    ("ruler", "Правитель"),
                    ("lover", "Любовник"),
                    ("hero", "Герой"),
                ],
                help_text="Если заполнено, курс поднимается наверх у людей с этим архетипом.",
                max_length=20,
                verbose_name="Рекомендован архетипу",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="order",
            field=models.PositiveIntegerField(default=100, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Длительность, мин"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("free", "Бесплатный — «Искатель»"),
                    ("paid", "Платный курс — разовая покупка"),
                    ("club", "Только для членов клуба — «Творец»"),
                    ("mage", "Только личное ведение — «Маг»"),
                ],
                default="free",
                max_length=10,
                verbose_name="Уровень доступа",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(
                default=False,
                help_text="Открыт всем, даже если курс закрытый.",
                verbose_name="Доступен для предпросмотра",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Файл хранится вне публичной папки и отдаётся только тем, у кого есть доступ.",
                null=True,
                storage=lms.storage.protected_storage,
                upload_to="lessons/videos/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "mkv", "webm"]
                    )
                ],
                verbose_name="Видеофайл (загрузка на сайт)",
            ),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название раздела"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел курса",
                "verbose_name_plural": "Разделы курса",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="lms.module",
                verbose_name="Раздел",
            ),
        ),
        migrations.CreateModel(
            name="CourseAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Выдан"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Например: «оплата #128» или «подарок».",
                        max_length=255,
                        verbose_name="Основание",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="lms.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к курсу",
                "verbose_name_plural": "Доступы к курсам",
                "ordering": ["-granted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"), name="lms_unique_course_access"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Пройден"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Открыт"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Пройден в"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="lms.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по уроку",
                "verbose_name_plural": "Прогресс по урокам",
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "lesson"), name="lms_unique_progress_per_lesson"
                    )
                ],
            },
        ),
    ]
