# Generated by Django 6.0.7 on 2026-07-29 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название компании')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('target_stage', models.CharField(blank=True, choices=[('new', 'Новый лид'), ('form_filled', 'Анкета заполнена'), ('slot_booked', 'Слот забронирован'), ('session_done', 'Разбор проведен'), ('subscribed', 'Подписка оформлена'), ('closed_lost', 'Отказ / Закрыто')], max_length=20, null=True, verbose_name='Целевой этап лида')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'Новый лид'), ('form_filled', 'Анкета заполнена'), ('slot_booked', 'Слот забронирован'), ('session_done', 'Разбор проведен'), ('subscribed', 'Подписка оформлена'), ('closed_lost', 'Отказ / Закрыто')], default='new', max_length=20, verbose_name='Этап воронки')),
                ('source', models.CharField(default='Telegram', max_length=100, verbose_name='Источник трафика')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки менеджера')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Лид CRM',
                'verbose_name_plural': 'Лиды CRM',
            },
        ),
    ]
